# Zone7 Plugin Configuration

# Discord Command Settings
DiscordCommand:
  # Enable or Disable the Discord Command
  Enabled: true
  # Text Message displayed by the Discord Command
  TextMessage: "Join our Discord!"
  # Gradient Colors for the Text Message
  TextColor:
    - "#7289DA" # Start
    - "#8A91E6" # End
  # Discord Link displayed by the Command
  Link: "discord.gg/example"
  # Color of the Discord Link
  LinkColor: "#B9ABF8" # Light Blue

# Poke Command Settings
PokeCommand:
  # Enable or Disable the Poke Command
  Enabled: true

# Tips Feature Settings
TipsCommand:
  # Enable or Disable Tips Broadcast
  FeatureEnabled: true
  # Interval between Tips Messages in seconds (3600 seconds = 1 hour)
  Interval: 3600
  # List of Messages broadcasted as Tips
  Messages:
    - "&eDo you want a pet? Try out /pets"
    - "&aCheckout the shops at spawn!"
    - "&bWant ChestProtection? Do /cp to get more info!"
    - "&dClaim land by using /lands and /land claim"

# Flower Drop Feature Settings
FlowerDropFeature:
  # Enable or Disable Flower Drop Feature
  Enabled: true

# Arrow Trails Feature Settings
ArrowTrails:
  Enabled: true
  # Enable or Disable Arrow Trails
  Trails:
    Cupid:
      Particles:
        - HEART
    Bubbles:
      Particles:
        - BUBBLE_POP
        - BUBBLE_COLUMN_UP
  # Example Arrow Trail
  # Mystic: <-- Name of Bow/Crossbow
    # Particles:
      # - END_ROD <-- Particles to display
      # - ENCHANTMENT_TABLE <-- Particles 2
      # - HEART <-- Particles 3
      #  etc..

# Petting Feature Settings
PettingFeature:
  # Enable or Disable the Petting Feature
  Enabled: true
# Pet Messages used in the Petting Feature
PetMessages:
  - "gently pets"
  - "kindly pets"
  - "softly pets"
  - "affectionately pets"
  - "lovingly pets"
  - "warmly pets"
  - "carefully pets"
  - "tenderly pets"
  - "fondly pets"
  - "sweetly pets"
  - "cheerfully pets"
  - "happily pets"
  - "playfully pets"
  - "gently pets"
  - "joyfully pets"
  - "peacefully pets"
  - "pleasantly pets"
  - "politely pets"
  - "respectfully pets"
  - "sincerely pets"
  - "sympathetically pets"
  - "thoughtfully pets"
  - "cordially pets"
  - "delightedly pets"
  - "eagerly pets"
  - "enthusiastically pets"
  - "gratefully pets"
  - "keenly pets"
  - "merrily pets"
  - "optimistically pets"
  - "reassuringly pets"
  - "understandingly pets"
  - "compassionately pets"
  - "devotedly pets"
  - "generously pets"
  - "graciously pets"
  - "pets the head of"
  - "pets the belly of"
  - "scratches the ears of"