DiscordCommand:
  TextMessage: "Join our Discord!"
  TextColor:
    - "#7289DA"
    - "#8A91E6"
  Link: "discord.gg/example"
  LinkColor: "#B9ABF8"

TipsCommand:
  Enabled: true
  Interval: 3600 # in seconds (3600 seconds = 1 hour)
  Messages:
    - "&eDo you want a pet? Try out /pets"
    - "&aCheckout the shops at spawn!"
    - "&bWant ChestProtection? Do /cp to get more info!"
    - "&dClaim land by using /lands and /land claim"
